[package]
name = "sc-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
sc-types = { path = "../sc-types" }
serde = "1.0.197"
rmp-serde = "1.1.2"
